### ISSUE TITLE
Function to "reconfigure" SD card overwrites individual track titles with default preloaded items

### ISSUE THREAD

**Issue by Snublefot88** [winzkigermany/hoerbert-software#2]
Hi,
I recently bought hörbert and I am enjoying it very much 👍 (my son too ;-)
When I first got him in the summer 2020, I used the WIndows10/Beta version from the website to load some personal songs onto the included/preloaded "German songs" SD card and I also rearranged some songs between playlists. I remember that at that time the preloaded tracks just read 0, 1, 2, 3 in the playlist window and no actual titles. For the new songs I added from my library, the software would show the proper meta tag "title".

Now today / November 2020 (I believe still on the same software version) I wanted to add some more songs when the software asked me in a popup to reconfigure the SD card (not sure anymore about the exact wording). I said yes and the program worked on the card for a while.
Then I noticed that in each playlist, the first few songs actually showed the title names of the preloaded songs. However, as said above, I had changed the order of the songs and even deleted some of them already. The names were simply now attached to my own songs that were stored instead of the preloaded songs.

I can't reproduce the topic of course, but I am just wondering if this "reconfigure SD card function" (not sure of its purpose) should take into consideration that the songs may not be the songs from the initial load anymore.

I hope my description is understandable. If you have any follow up questions, please be in touch.
Thanks for a great product!

**Comment by winzkigermany** [comment]
Thank you for your feedback, I'm glad you like our product. Please accept my apologies for that problem.
Here are my thoughts: 

What the this software does when "reconfiguring" the contents:
In the 1.x version of this software, all the file names and meta data were stored in "hoerbert.xml". This was the only way for the hörbert software to remember the original file names. hörbert himself does *not* read that file, because hörbert solely depends on the file names are named 0.wav, 1.wav, 2.wav and so on on the memory cards .
In your case, obviously, hoerbert.xml and the contents of the card were not in sync.
So when "migrating" the card to the new format, the hörbert software 2.x reads hoerbert.xml and copies the file titles and names into metadata fields of the wav files. In your case, there was YOUR new wav file in some places, but hoerbert.xml was not updated accordingly before migration ran. (I can't guess, why. That would need deeper investigation).
In result, your wav file's metadata got overwritten by the contents of an outdated hoerbert.xml.
Since migration is a one-time action, this will not happen again with that card.

In any way, it's best to leave any hoerbert.xml or hoerbert.bak files alone, so no further automatism kicks in to "clean up" or "correct" and meta data.
This hoerbert 2.x software still updates hoerbert.xml for backward compatibility, so it should be possible to switch between old 1.x and new 2.x software, although I would not recommend that. It's merely a feature to keep bad things from happening when you accidentally use the old 1.x software again.

If something like this happens again or to more people, that would mean there is some problem in writing out a proper hoerbert.xml file in some cases. It would be inevitable to take a deeper look in that case. Possibly this is a one-time event, I only can apologize for the problem that occurred to you. I'm afraid that I will not be able to reproduce any other test case than the ones that have to fail: Updating WAV files without updating hoerbert.xml, then doing a migration, will result exactly in the problem you described.

Please feel free to step on my toes in case this happens again. I'll have an eye on this when testing the first non-Beta...

**Comment by Snublefot88** [comment]
Thanks for the detailed explanation! Don't worry too much, it just took me ten minutes to correct the titles by going through the content list from your website. :-)

Coming to think of it, it may actually not have been obvious to me exactly "when" the XML-file is updated. Is it only when hitting the green "eject button"?
Because I may not have done that when I first loaded hörbert with own songs sinceI assumed the button would do the same as the windows eject-function. Maybe at that time the XML file did get out of sync (I didn't touch it manually)

Again, I love the way that hörbert works the way it works! Keep up the great work!
Best regards from Hamburg,
Hendrik
