### ISSUE TITLE
SD Card device not detected on Ubuntu 18.04

### ISSUE THREAD

**Issue by johannes-graeter** [winzkigermany/hoerbert-software#7]
Hi there,

thx for the awesome hoerbert :)
Just tried to use the appimage suppied on your homepage to upload some music on the sd card.
Unfortunately the software does not detect the SD Card device even though it is detected by the OS. Other devices such as USB drives are shown in the softwares dropdown.

Any ideas?

**Comment by johannes-graeter** [comment]
Adding the source manually in the menu worked though.

**Comment by winzkigermany** [comment]
Thanks a lot for bringing this up - and finding the intended fallback :-)

That's why we added the manual way in the menu to add the source drive.
On linux, you may even add any directory manually and play around with it. Afterwards simply copy that directory to an SD card.

Since USB device detection seems to be unreliable for some distros more than for others, I'm afraid there's nothing we can do.
The manual addition of the memory card's path seems to be the best fallback at the moment.
