### ISSUE TITLE
Hoerbert Software crashes when trying to access advanced settings

### ISSUE THREAD

**Issue by sensslen** [winzkigermany/hoerbert-software#8]
When trying to access advanced settings dialog while old hoerbert variant is selected, the software crashes

**Comment by sensslen** [comment]
This is fixed in #5

**Comment by winzkigermany** [comment]
Thank you very much for bringing this up, along with a proposed fix.

In our codebase, the fix is in [https://github.com/winzkigermany/hoerbert-software/commit/eda2c3a2ef0515ef913c9a20a27adb3a70ed059c](https://github.com/winzkigermany/hoerbert-software/commit/eda2c3a2ef0515ef913c9a20a27adb3a70ed059c)
